import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/components/auth/AuthProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home | Artifact",
  description: "Generated by create next app",
  icons: {
    icon: '/favicons/icon-32.png', // This overrides the default favicon.ico
    shortcut: '/favicons/icon-32.png',
    apple: '/favicons/icon-180.png',
    other: [
      { url: '/favicons/icon-16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicons/icon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicons/icon-64.png', sizes: '64x64', type: 'image/png' },
      { url: '/favicons/icon-128.png', sizes: '128x128', type: 'image/png' },
      { url: '/favicons/icon-256.png', sizes: '256x256', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
